"""add_include_subdomains_to_documentation_sources

Revision ID: 0a2197b4e241
Revises: e46de09d8fa5
Create Date: 2025-07-06 10:58:04.283836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a2197b4e241'
down_revision: Union[str, Sequence[str], None] = 'e46de09d8fa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first, then set default and make non-nullable (SQLite compatibility)
    op.add_column('documentation_sources', sa.Column('include_subdomains', sa.Boolean(), nullable=True))
    
    # Update existing rows to have default value False
    op.execute("UPDATE documentation_sources SET include_subdomains = 0 WHERE include_subdomains IS NULL")
    
    # Now alter to NOT NULL (SQLite doesn't support this directly, but the data is clean)
    # We'll leave it nullable since SQLite can't alter to NOT NULL, but all values are set
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documentation_sources', 'include_subdomains')
    # ### end Alembic commands ###
