"""add_documentation_status_enum

Revision ID: 2e2e94d9f4d6
Revises: 0a2197b4e241
Create Date: 2025-07-06 12:24:06.845067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e2e94d9f4d6'
down_revision: Union[str, Sequence[str], None] = '0a2197b4e241'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Simply drop the old table and recreate with proper enum constraint
    op.drop_table('documentation_sources')
    
    # Create new table with DocumentationStatus enum constraint
    op.create_table('documentation_sources',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('url', sa.String(), nullable=False),
        sa.Column('source_type', sa.Enum('API', 'GUIDE', 'REFERENCE', 'TUTORIAL', name='sourcetype'), nullable=False),
        sa.Column('crawl_depth', sa.Integer(), nullable=False),
        sa.Column('update_frequency', sa.Enum('HOURLY', 'DAILY', 'WEEKLY', name='updatefrequency'), nullable=False),
        sa.Column('selectors', sa.Text(), nullable=True),
        sa.Column('allow_patterns', sa.Text(), nullable=True),
        sa.Column('ignore_patterns', sa.Text(), nullable=True),
        sa.Column('include_subdomains', sa.Boolean(), nullable=True),
        sa.Column('last_scraped', sa.DateTime(), nullable=True),
        sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'PAUSED', 'STALE', name='documentationstatus'), nullable=False, default='NOT_STARTED'),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('source_metadata', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop current table and recreate with String status
    op.drop_table('documentation_sources')
    
    # Recreate original table structure with String status
    op.create_table('documentation_sources',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('url', sa.String(), nullable=False),
        sa.Column('source_type', sa.Enum('API', 'GUIDE', 'REFERENCE', 'TUTORIAL', name='sourcetype'), nullable=False),
        sa.Column('crawl_depth', sa.Integer(), nullable=False),
        sa.Column('update_frequency', sa.Enum('HOURLY', 'DAILY', 'WEEKLY', name='updatefrequency'), nullable=False),
        sa.Column('selectors', sa.Text(), nullable=True),
        sa.Column('allow_patterns', sa.Text(), nullable=True),
        sa.Column('ignore_patterns', sa.Text(), nullable=True),
        sa.Column('include_subdomains', sa.Boolean(), nullable=True),
        sa.Column('last_scraped', sa.DateTime(), nullable=True),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('source_metadata', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    
    # ### end Alembic commands ###
