"""Initial schema - clean setup

Revision ID: 71cfde59995f
Revises: 
Create Date: 2025-07-05 11:03:45.065591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71cfde59995f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('repository_path', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'IDLE', 'COMPLETED', 'TERMINATED', name='agentstatus'), nullable=False),
    sa.Column('claude_pid', sa.Integer(), nullable=True),
    sa.Column('capabilities', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=False),
    sa.Column('agent_metadata', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analysis_cache',
    sa.Column('cache_key', sa.String(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('analysis_result', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_accessed', sa.DateTime(), nullable=False),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('cache_key')
    )
    op.create_table('chat_rooms',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('repository_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('room_metadata', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('documentation_sources',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('source_type', sa.Enum('API', 'GUIDE', 'REFERENCE', 'TUTORIAL', name='sourcetype'), nullable=False),
    sa.Column('crawl_depth', sa.Integer(), nullable=False),
    sa.Column('update_frequency', sa.Enum('HOURLY', 'DAILY', 'WEEKLY', name='updatefrequency'), nullable=False),
    sa.Column('selectors', sa.Text(), nullable=True),
    sa.Column('ignore_patterns', sa.Text(), nullable=True),
    sa.Column('last_scraped', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('source_metadata', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('error_patterns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('repository_path', sa.String(), nullable=False),
    sa.Column('pattern_name', sa.String(), nullable=False),
    sa.Column('error_signature', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('typical_causes', sa.Text(), nullable=True),
    sa.Column('suggested_solutions', sa.Text(), nullable=True),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.Column('last_occurrence', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_error_patterns_repository_path'), 'error_patterns', ['repository_path'], unique=False)
    op.create_table('file_watchers',
    sa.Column('project_path', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('last_event_at', sa.DateTime(), nullable=True),
    sa.Column('files_watched', sa.Integer(), nullable=False),
    sa.Column('events_processed', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('configuration', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('project_path')
    )
    op.create_table('agent_capabilities',
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('capability', sa.String(), nullable=False),
    sa.Column('proficiency_level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_sessions.id'], ),
    sa.PrimaryKeyConstraint('agent_id', 'capability')
    )
    op.create_table('analysis_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_path', sa.String(), nullable=False),
    sa.Column('session_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('assigned_agent_id', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('files_analyzed', sa.Integer(), nullable=False),
    sa.Column('files_total', sa.Integer(), nullable=False),
    sa.Column('languages_detected', sa.Text(), nullable=True),
    sa.Column('treesummary_path', sa.String(), nullable=True),
    sa.Column('watching_enabled', sa.Boolean(), nullable=False),
    sa.Column('analysis_metadata', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_agent_id'], ['agent_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('room_name', sa.String(), nullable=False),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('mentions', sa.Text(), nullable=True),
    sa.Column('message_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['room_name'], ['chat_rooms.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documentation_entries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('extracted_at', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('section_type', sa.Enum('CONTENT', 'CODE', 'EXAMPLE', 'API', name='sectiontype'), nullable=False),
    sa.Column('entry_metadata', sa.Text(), nullable=True),
    sa.Column('links', sa.Text(), nullable=True),
    sa.Column('code_examples', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['documentation_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash')
    )
    op.create_table('memories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('repository_path', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('entry_type', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('misc_data', sa.Text(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('usefulness_score', sa.Float(), nullable=False),
    sa.Column('accessed_count', sa.Integer(), nullable=False),
    sa.Column('referenced_count', sa.Integer(), nullable=False),
    sa.Column('last_accessed', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memories_category'), 'memories', ['category'], unique=False)
    op.create_index(op.f('ix_memories_entry_type'), 'memories', ['entry_type'], unique=False)
    op.create_index(op.f('ix_memories_repository_path'), 'memories', ['repository_path'], unique=False)
    op.create_table('room_memberships',
    sa.Column('room_name', sa.String(), nullable=False),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['room_name'], ['chat_rooms.name'], ),
    sa.PrimaryKeyConstraint('room_name', 'agent_name')
    )
    op.create_table('tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('repository_path', sa.String(), nullable=False),
    sa.Column('task_type', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='taskstatus'), nullable=False),
    sa.Column('assigned_agent_id', sa.String(), nullable=True),
    sa.Column('parent_task_id', sa.String(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('results', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_agent_id'], ['agent_sessions.id'], ),
    sa.ForeignKeyConstraint(['parent_task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('code_documentation_links',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('symbol_name', sa.String(), nullable=False),
    sa.Column('symbol_type', sa.String(), nullable=False),
    sa.Column('documentation_entry_id', sa.String(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['documentation_entry_id'], ['documentation_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dead_code_findings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('analysis_session_id', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('finding_type', sa.String(), nullable=False),
    sa.Column('symbol_name', sa.String(), nullable=True),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('impact_level', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('false_positive', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_session_id'], ['analysis_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documentation_changes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('entry_id', sa.String(), nullable=False),
    sa.Column('change_type', sa.String(), nullable=False),
    sa.Column('old_content_hash', sa.String(), nullable=True),
    sa.Column('new_content_hash', sa.String(), nullable=True),
    sa.Column('impact_level', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['documentation_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documentation_embeddings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('entry_id', sa.String(), nullable=False),
    sa.Column('embedding', sa.Text(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['documentation_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('error_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('repository_path', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=True),
    sa.Column('task_id', sa.String(), nullable=True),
    sa.Column('error_type', sa.String(), nullable=False),
    sa.Column('error_category', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('environment', sa.Text(), nullable=True),
    sa.Column('attempted_solution', sa.Text(), nullable=True),
    sa.Column('resolution_status', sa.String(), nullable=False),
    sa.Column('resolution_details', sa.Text(), nullable=True),
    sa.Column('pattern_id', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_sessions.id'], ),
    sa.ForeignKeyConstraint(['pattern_id'], ['error_patterns.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_error_logs_repository_path'), 'error_logs', ['repository_path'], unique=False)
    op.create_table('file_analyses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('analysis_session_id', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('relative_path', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('line_count', sa.Integer(), nullable=True),
    sa.Column('complexity_score', sa.Integer(), nullable=True),
    sa.Column('maintainability_score', sa.Integer(), nullable=True),
    sa.Column('symbols_extracted', sa.Integer(), nullable=False),
    sa.Column('analysis_timestamp', sa.DateTime(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('analysis_data', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_session_id'], ['analysis_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('symbol_dependencies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_file', sa.String(), nullable=False),
    sa.Column('source_symbol', sa.String(), nullable=False),
    sa.Column('target_file', sa.String(), nullable=False),
    sa.Column('target_symbol', sa.String(), nullable=True),
    sa.Column('dependency_type', sa.String(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('analysis_session_id', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_session_id'], ['analysis_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_dependencies',
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('depends_on_task_id', sa.String(), nullable=False),
    sa.Column('dependency_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('task_id', 'depends_on_task_id')
    )
    op.create_table('tool_call_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('repository_path', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=True),
    sa.Column('tool_name', sa.String(), nullable=False),
    sa.Column('parameters', sa.Text(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('execution_time', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_sessions.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_call_logs_repository_path'), 'tool_call_logs', ['repository_path'], unique=False)
    op.create_table('learning_entries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('repository_path', sa.String(), nullable=False),
    sa.Column('learning_type', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('lesson', sa.Text(), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('source_error_id', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('applicability_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('applied_count', sa.Integer(), nullable=False),
    sa.Column('success_rate', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['source_error_id'], ['error_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_entries_repository_path'), 'learning_entries', ['repository_path'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_learning_entries_repository_path'), table_name='learning_entries')
    op.drop_table('learning_entries')
    op.drop_index(op.f('ix_tool_call_logs_repository_path'), table_name='tool_call_logs')
    op.drop_table('tool_call_logs')
    op.drop_table('task_dependencies')
    op.drop_table('symbol_dependencies')
    op.drop_table('file_analyses')
    op.drop_index(op.f('ix_error_logs_repository_path'), table_name='error_logs')
    op.drop_table('error_logs')
    op.drop_table('documentation_embeddings')
    op.drop_table('documentation_changes')
    op.drop_table('dead_code_findings')
    op.drop_table('code_documentation_links')
    op.drop_table('tasks')
    op.drop_table('room_memberships')
    op.drop_index(op.f('ix_memories_repository_path'), table_name='memories')
    op.drop_index(op.f('ix_memories_entry_type'), table_name='memories')
    op.drop_index(op.f('ix_memories_category'), table_name='memories')
    op.drop_table('memories')
    op.drop_table('documentation_entries')
    op.drop_table('chat_messages')
    op.drop_table('analysis_sessions')
    op.drop_table('agent_capabilities')
    op.drop_table('file_watchers')
    op.drop_index(op.f('ix_error_patterns_repository_path'), table_name='error_patterns')
    op.drop_table('error_patterns')
    op.drop_table('documentation_sources')
    op.drop_table('chat_rooms')
    op.drop_table('analysis_cache')
    op.drop_table('agent_sessions')
    # ### end Alembic commands ###
