"""add website page model with multiple content formats

Revision ID: ca00e26ec31b
Revises: 2e2e94d9f4d6
Create Date: 2025-07-06 13:43:43.500004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca00e26ec31b'
down_revision: Union[str, Sequence[str], None] = '2e2e94d9f4d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('website_pages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('normalized_url', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('raw_html', sa.Text(), nullable=True),
    sa.Column('markdown_content', sa.Text(), nullable=True),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('html_hash', sa.String(), nullable=True),
    sa.Column('markdown_hash', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('extracted_at', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('page_metadata', sa.Text(), nullable=True),
    sa.Column('links', sa.Text(), nullable=True),
    sa.Column('code_examples', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['documentation_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_url', 'source_id', name='_website_page_url_source_uc')
    )
    op.create_index(op.f('ix_website_pages_normalized_url'), 'website_pages', ['normalized_url'], unique=False)
    
    # Use batch mode for SQLite compatibility
    with op.batch_alter_table('documentation_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website_page_id', sa.String(), nullable=True))
        batch_op.create_foreign_key('fk_documentation_entries_website_page', 'website_pages', ['website_page_id'], ['id'])

    with op.batch_alter_table('scraped_urls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website_page_id', sa.String(), nullable=True))
        batch_op.create_foreign_key('fk_scraped_urls_website_page', 'website_pages', ['website_page_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Use batch mode for SQLite compatibility
    with op.batch_alter_table('scraped_urls', schema=None) as batch_op:
        batch_op.drop_constraint('fk_scraped_urls_website_page', type_='foreignkey')
        batch_op.drop_column('website_page_id')
    
    with op.batch_alter_table('documentation_entries', schema=None) as batch_op:
        batch_op.drop_constraint('fk_documentation_entries_website_page', type_='foreignkey')
        batch_op.drop_column('website_page_id')
    
    op.drop_index(op.f('ix_website_pages_normalized_url'), table_name='website_pages')
    op.drop_table('website_pages')
    # ### end Alembic commands ###
